/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 9.0.0
board: MIMXRT1010-EVK
pin_labels:
- {pin_num: '3', pin_signal: GPIO_09, label: UART1_RXD, identifier: UART1_RXD}
- {pin_num: '2', pin_signal: GPIO_10, label: UART1_TXD, identifier: UART1_TXD}
- {pin_num: '65', pin_signal: GPIO_SD_10, label: FlexSPI_CLK, identifier: FlexSPI_CLK}
- {pin_num: '66', pin_signal: GPIO_SD_09, label: FlexSPI_D0_A, identifier: FlexSPI_D0_A}
- {pin_num: '68', pin_signal: GPIO_SD_07, label: FlexSPI_D1_A, identifier: FlexSPI_D1_A}
- {pin_num: '67', pin_signal: GPIO_SD_08, label: FlexSPI_D2_A, identifier: FlexSPI_D2_A}
- {pin_num: '64', pin_signal: GPIO_SD_11, label: FlexSPI_D3_A, identifier: FlexSPI_D3_A}
- {pin_num: '69', pin_signal: GPIO_SD_06, label: FlexSPI_SS0, identifier: FlexSPI_SS0}
- {pin_num: '1', pin_signal: GPIO_11, label: GPIO_11, identifier: GPIO_11;OLED_DC}
- {pin_num: '58', pin_signal: GPIO_AD_02, label: 'ADC12_2/J26[12]/J56[16]', identifier: ADC12_2;LPSPI1_PCS1}
- {pin_num: '55', pin_signal: GPIO_AD_05, label: 'LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1]', identifier: LPSPI1_PCS0;OLED_RST}
- {pin_num: '13', pin_signal: GPIO_00, label: 'AUD_INT/U10[15]', identifier: AUD_INT;INT_I2C1}
- {pin_num: '49', pin_signal: GPIO_AD_08, label: 'JTAG_TRSTB/J55[10]', identifier: JTAG_TRSTB;OLED_EN}
- {pin_num: '47', pin_signal: GPIO_AD_10, label: 'ADC12_5/JTAG_TDI/J55[8]/J26[6]', identifier: ADC12_5;JOY_X}
- {pin_num: '46', pin_signal: GPIO_AD_11, label: WDOG_B/JTAG_MOD, identifier: WDOG_B;JOY_Y}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: LPUART1, signal: RXD, pin_signal: GPIO_09, slew_rate: Slow, software_input_on: Disable, open_drain: Disable, drive_strength: R0_4,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '2', peripheral: LPUART1, signal: TXD, pin_signal: GPIO_10, slew_rate: Slow, software_input_on: Disable, open_drain: Disable, drive_strength: R0_4,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '11', peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_02, slew_rate: Slow, software_input_on: Enable, open_drain: Enable, drive_strength: R0_4, pull_keeper_select: Keeper,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '12', peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_01, slew_rate: Slow, software_input_on: Enable, open_drain: Enable, drive_strength: R0_4, pull_keeper_select: Keeper,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '13', peripheral: GPIO1, signal: 'gpiomux_io, 00', pin_signal: GPIO_00, identifier: INT_I2C1, direction: INPUT, gpio_interrupt: kGPIO_IntFallingEdge,
    software_input_on: Disable, open_drain: Disable, pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '47', peripheral: ADC1, signal: 'IN, 10', pin_signal: GPIO_AD_10, identifier: JOY_X}
  - {pin_num: '46', peripheral: ADC1, signal: 'IN, 11', pin_signal: GPIO_AD_11, identifier: JOY_Y}
  - {pin_num: '52', peripheral: LPSPI1, signal: SCK, pin_signal: GPIO_AD_06, slew_rate: Slow, software_input_on: Disable, open_drain: Disable, drive_strength: R0_4,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '56', peripheral: LPSPI1, signal: SDO, pin_signal: GPIO_AD_04, slew_rate: Slow, software_input_on: Disable, open_drain: Disable, drive_strength: R0_4,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '58', peripheral: LPSPI1, signal: PCS1, pin_signal: GPIO_AD_02, identifier: LPSPI1_PCS1}
  - {pin_num: '49', peripheral: GPIO1, signal: 'gpiomux_io, 22', pin_signal: GPIO_AD_08, identifier: OLED_EN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '55', peripheral: GPIO1, signal: 'gpiomux_io, 19', pin_signal: GPIO_AD_05, identifier: OLED_RST, direction: OUTPUT}
  - {pin_num: '1', peripheral: GPIO1, signal: 'gpiomux_io, 11', pin_signal: GPIO_11, identifier: OLED_DC, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of INT_I2C1 on GPIO_00 (pin 13) */
  gpio_pin_config_t INT_I2C1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntFallingEdge
  };
  /* Initialize GPIO functionality on GPIO_00 (pin 13) */
  GPIO_PinInit(GPIO1, 0U, &INT_I2C1_config);
  /* Enable GPIO pin interrupt on GPIO_00 (pin 13) */
  GPIO_PortEnableInterrupts(GPIO1, 1U << 0U);

  /* GPIO configuration of OLED_DC on GPIO_11 (pin 1) */
  gpio_pin_config_t OLED_DC_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_11 (pin 1) */
  GPIO_PinInit(GPIO1, 11U, &OLED_DC_config);

  /* GPIO configuration of OLED_RST on GPIO_AD_05 (pin 55) */
  gpio_pin_config_t OLED_RST_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_05 (pin 55) */
  GPIO_PinInit(GPIO1, 19U, &OLED_RST_config);

  /* GPIO configuration of OLED_EN on GPIO_AD_08 (pin 49) */
  gpio_pin_config_t OLED_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_08 (pin 49) */
  GPIO_PinInit(GPIO1, 22U, &OLED_EN_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_00_GPIOMUX_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_01_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_02_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_09_LPUART1_RXD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_10_LPUART1_TXD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_11_GPIOMUX_IO11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_02_LPSPI1_PCS1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_04_LPSPI1_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_05_GPIOMUX_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_06_LPSPI1_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_08_GPIOMUX_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_10_GPIOMUX_IO24, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_11_GPIOMUX_IO25, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_SEL(0x00U)      
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_00_GPIOMUX_IO00, 0xD0A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_01_LPI2C1_SDA, 0xD8A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_02_LPI2C1_SCL, 0xD8A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_09_LPUART1_RXD, 0x10A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_10_LPUART1_TXD, 0x10A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_04_LPSPI1_SDO, 0x10A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_06_LPSPI1_SCK, 0x10A0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
