/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK 0x480800U /*!< Select GPIO1 or GPIO2: affected bits mask */

/* GPIO_09 (number 3), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_10 (number 2), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                      TXD   /*!< Signal name */

/* GPIO_02 (number 11), I2C1_SCL/U10[17]/J57[20]/U26[4] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C1_SCL_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_I2C1_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_01 (number 12), I2C1_SDA/U10[18]/J57[18]/U26[6] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C1_SDA_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_I2C1_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_00 (number 13), AUD_INT/U10[15] */
/* Routed pin properties */
#define BOARD_INITPINS_INT_I2C1_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_INT_I2C1_SIGNAL                                gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_INT_I2C1_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_AD_10 (number 47), ADC12_5/JTAG_TDI/J55[8]/J26[6] */
/* Routed pin properties */
#define BOARD_INITPINS_JOY_X_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_JOY_X_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITPINS_JOY_X_CHANNEL                                         10U   /*!< Signal channel */

/* GPIO_AD_11 (number 46), WDOG_B/JTAG_MOD */
/* Routed pin properties */
#define BOARD_INITPINS_JOY_Y_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_JOY_Y_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITPINS_JOY_Y_CHANNEL                                         11U   /*!< Signal channel */

/* GPIO_AD_06 (number 52), LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_AD_04 (number 56), LPSPI1_SDO/J57[8]/U27[5] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDO_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDO_SIGNAL                                     SDO   /*!< Signal name */

/* GPIO_AD_02 (number 58), ADC12_2/J26[12]/J56[16] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS1_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS1_SIGNAL                                   PCS1   /*!< Signal name */

/* GPIO_AD_08 (number 49), JTAG_TRSTB/J55[10] */
/* Routed pin properties */
#define BOARD_INITPINS_OLED_EN_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_OLED_EN_SIGNAL                                 gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_OLED_EN_CHANNEL                                       22U   /*!< Signal channel */

/* GPIO_AD_05 (number 55), LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1] */
/* Routed pin properties */
#define BOARD_INITPINS_OLED_RST_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_OLED_RST_SIGNAL                                gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_OLED_RST_CHANNEL                                      19U   /*!< Signal channel */

/* GPIO_11 (number 1), GPIO_11 */
/* Routed pin properties */
#define BOARD_INITPINS_OLED_DC_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_OLED_DC_SIGNAL                                 gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_OLED_DC_CHANNEL                                       11U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
